wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.6
    cli_version: 0.15.3
    framework: huggingface
    huggingface_version: 4.38.0.dev0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1707093761.043754
    t:
      1:
      - 1
      - 11
      - 49
      - 50
      - 51
      - 55
      2:
      - 1
      - 11
      - 49
      - 50
      - 51
      - 55
      3:
      - 17
      - 23
      4: 3.10.6
      5: 0.15.3
      6: 4.38.0.dev0
      8:
      - 5
